// {student_name:String,
// student_fathers_name:String,
// student_mothers_name:String,
// student_guardians_name:String,
// student_address_name:String,
// student_primary_ph_no:String,
// student_fathers_ph_no:String,
// student_mothers_ph_no:String,
// student_guardians_ph_no:String,
// student_aadhar_no:
// student_religion:String,
// student_cast:String,
// student_RTE:
// student_date_of_birth:String,
// student_place_of_birth:String,
// student_divisions:[{
// type: Schema.Types.ObjectId,
// ref: division
// }],
// student_enable_status:String,
// student_notification_status:String,
// student_notification_profile:String,
// student_class:String,
// student_acad_yr:String,
// student_fees:{
// admission_fees: Number,
// main_fees: [{
// fee_title: String,
// total_fees: Number,
// total_fees_paid: Number,
// total_fees_pending: Number,
// sub_of_fees: [{
// sub_fees_title: String,
// sub_amount: Number,
// sub_paid: Number,
// sub_pending: Number,
// fee_priority: Number,
// }]
// }],
// extra_fee: [{
// extra_fee_title: String,
// extra_total_fee: Number,
// extra_total_fee_paid: Number,
// extra_total_fee_pending: Number,
// extra_sub_of_fees: [{
// extra_sub_fees_title: String,
// extra_sub_amount: Number,
// extra_sub_paid: Number,
// extra_sub_pending: Number,
// extra_fee_priority: Number,
// }]
// }]
// },
// student_fee_total:Number,
// student_fee_pending:Number,
// student_discount_amount:Number,
// student_discount_percentage:Number,
// student_reminder:Date,
// student_username:String,
// student_password:String,
//  }
//
// {"student_name":"asim",
// "student_fathers_name":"fazal",
// "student_mothers_name":"yasmin",
// "student_guardians_name":"saaniya",
// "student_address_name":"pune",
// "student_primary_ph_no":"+917620451246",
// "student_fathers_ph_no":"+917620451246",
// "student_mothers_ph_no":"+910000000000",
// "student_guardians_ph_no":"+918888888888",
// "student_aadhar_no":1234567890,
// "student_religion":"Muslim",
// "student_cast":"General",
// "student_RTE":false,
// "student_date_of_birth":"04-10-1989",
// "student_place_of_birth":"pune",
// "student_divisions":["7C","8A","9B"],
// "student_enable_status":true,
// "student_notification_status":"disabled",
// "student_notification_profile":"No Profile",
// "student_username":"wergweryhv2",
// "student_password":"awergwethjate",
// }
